# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='IntentEntities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=140)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_entries', to='rasacore.Intents')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='rasacore.Intents')),
            ],
        ),
    ]
