# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0002_entities_intententities'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentUserSays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersays', to='rasacore.Intents')),
            ],
        ),
    ]
