# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0004_auto_20171115_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intententities',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_entities', to='rasacore.Entities'),
        ),
    ]
