# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0005_auto_20171115_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(choices=[('spacy_sklearn', 'Spacy-Sklearn')], default='spacy_sklearn', max_length=70)),
            ],
            options={
                'verbose_name': 'Training',
            },
        ),
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='entities',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterModelOptions(
            name='intententities',
            options={'verbose_name': 'Intent Entity', 'verbose_name_plural': 'Intent Entities'},
        ),
        migrations.AlterModelOptions(
            name='intents',
            options={'verbose_name': 'Intent', 'verbose_name_plural': 'Intents'},
        ),
        migrations.AlterModelOptions(
            name='intentusersays',
            options={'verbose_name': 'Intent User Say', 'verbose_name_plural': 'Intent User Says'},
        ),
    ]
