# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0007_auto_20171115_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='name',
            field=models.SlugField(max_length=70),
        ),
        migrations.AlterField(
            model_name='entities',
            name='name',
            field=models.SlugField(max_length=70),
        ),
        migrations.AlterField(
            model_name='intents',
            name='name',
            field=models.SlugField(max_length=70),
        ),
    ]
