# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0009_storyactionsresponses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storyactionsresponses',
            old_name='action',
            new_name='story_action',
        ),
    ]
