# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0010_auto_20171115_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseButtons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('payload', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
            },
        ),
        migrations.AlterModelOptions(
            name='storyactionsresponses',
            options={'verbose_name': 'Action response', 'verbose_name_plural': 'Action responses'},
        ),
        migrations.AddField(
            model_name='responsebuttons',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='rasacore.StoryActionsResponses'),
        ),
    ]
