# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0011_auto_20171115_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntentEntities',
            new_name='IntentUserSaysEntities',
        ),
        migrations.AlterModelOptions(
            name='intentusersaysentities',
            options={'verbose_name': 'User Says Entity', 'verbose_name_plural': 'User Says Entities'},
        ),
        migrations.RemoveField(
            model_name='intentusersaysentities',
            name='intent',
        ),
        migrations.AddField(
            model_name='intentusersaysentities',
            name='usersay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='rasacore.IntentUserSays'),
            preserve_default=False,
        ),
    ]
