# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0014_intentusersaysentities_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentusersaysentities',
            name='end',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='intentusersaysentities',
            name='start',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
