# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0016_auto_20171116_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_actions', to='rasacore.Actions')),
            ],
        ),
        migrations.RenameModel(
            old_name='StoryActionsResponses',
            new_name='IntentActionsResponses',
        ),
        migrations.RemoveField(
            model_name='storyactions',
            name='action',
        ),
        migrations.RemoveField(
            model_name='storyactions',
            name='story',
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
        migrations.RemoveField(
            model_name='intentactionsresponses',
            name='story_action',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='intent',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='level',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='intents',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='rasacore.Stories'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StoryActions',
        ),
        migrations.AddField(
            model_name='intentactions',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rasacore.Stories'),
        ),
        migrations.AddField(
            model_name='intentactionsresponses',
            name='intent_action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='rasacore.IntentActions'),
            preserve_default=False,
        ),
    ]
