# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasacore', '0017_auto_20171117_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intentactions',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='rasacore.Intents'),
        ),
    ]
